import requests
import json

token = "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"  
hello = """  Analyze the following code snippet extracted from a GitHub repository. Determine whether the code was generated by AI or written by a human. Evaluate the code's efficiency, readability, and logical structure.
 Additionally, provide an assessment of the developer's skill level, categorizing them as junior, mid-level, senior, or novice based on the code quality. "
from agent.tasks import run_task

def main():
    while True:
        task = input("Task (generate/debug/explain/exit): ")
        if task == "exit":
            break
        user_input = input("Enter your input: ")
        output = run_task(task, user_input)
        print("OUTPUT:", output)

if __name__ == "__main__":
    main()

"""
response = requests.post(
    url="https://openrouter.ai/api/v1/chat/completions",
    headers={
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    },
    data=json.dumps({
        "model": "deepseek/deepseek-r1-0528-qwen3-8b:free",
        "messages": [
            {
                "role": "user",
                "content": hello
            }
        ],
    })
).json()  
ai_response = response['choices'][0]['message']['content']
print(ai_response)  